"""
scripts/build_phase5_notebook.py
Génère notebooks/phase5_evaluation.ipynb — PRD v3.0
Usage : python scripts/build_phase5_notebook.py
"""
import json
from pathlib import Path


def md(*lines):
    return {"cell_type": "markdown", "id": None, "metadata": {}, "source": list(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": None,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }


cells_raw = [
    # ── Titre ─────────────────────────────────────────────────────────────────
    md(
        "# Phase 5 — Evaluation du pipeline YouTube Quality Analyzer (PRD v3.0)\n",
        "\n",
        "Ce notebook agregge tous les resultats d'evaluation (H1-H5) et produit les visualisations finales.\n",
        "\n",
        "**Hypotheses :**\n",
        "- H1 : Pearson r >= 0.60 / Spearman >= 0.55\n",
        "- H2 : DeltaPearson(multi-agents - LLM unique) > 0.10\n",
        "- H3 : Contribution A4 > A3 > A5\n",
        "- H4 : Gain F1 CoT/ToT/Tools vs prompt direct >= +15 pts (AC-09)\n",
        "- H5 : Score pertinence A7 ameliore satisfaction (Wilcoxon p < 0.05)",
    ),
    # ── Setup ─────────────────────────────────────────────────────────────────
    code(
        "import sys, json\n",
        "from pathlib import Path\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.gridspec as gridspec\n",
        "\n",
        "ROOT = Path('..').resolve()\n",
        "sys.path.insert(0, str(ROOT))\n",
        "\n",
        "RESULTS_DIR = ROOT / 'evaluation' / 'results'\n",
        "GOLD_PATH   = ROOT / 'data' / 'gold_standard' / 'gold_standard.jsonl'\n",
        "PREDS_PATH  = ROOT / 'data' / 'predictions' / 'pipeline_predictions.jsonl'\n",
        "\n",
        "RESULTS_DIR.mkdir(parents=True, exist_ok=True)\n",
        "plt.rcParams.update({'figure.dpi': 120, 'font.size': 11})\n",
        "print('Configuration OK — ROOT:', ROOT)",
    ),
    # ── 1. Chargement ─────────────────────────────────────────────────────────
    md("## 1. Chargement des resultats JSON"),
    code(
        "def load_result(filename):\n",
        "    path = RESULTS_DIR / filename\n",
        "    if not path.exists():\n",
        "        print(f'  [MANQUANT] {filename} — lancez le script correspondant')\n",
        "        return {}\n",
        "    with open(path, encoding='utf-8') as f:\n",
        "        return json.load(f)\n",
        "\n",
        "metrics      = load_result('metrics_report.json')\n",
        "baseline_cmp = load_result('baseline_comparison.json')\n",
        "ablation     = load_result('ablation_study.json')\n",
        "errors       = load_result('error_analysis.json')\n",
        "\n",
        "print('Fichiers charges :')\n",
        "for name, data in [('metrics_report', metrics), ('baseline_comparison', baseline_cmp),\n",
        "                   ('ablation_study', ablation), ('error_analysis', errors)]:\n",
        "    status = f'{len(data)} cles' if data else 'ABSENT'\n",
        "    print(f'  {name:<25} {status}')",
    ),
    # ── 2. H1 ─────────────────────────────────────────────────────────────────
    md("## 2. H1 — Correlation Pearson + Spearman (Score_Global vs gold_score)"),
    code(
        "if metrics:\n",
        "    r    = metrics.get('pearson_r', float('nan'))\n",
        "    rho  = metrics.get('spearman_r', float('nan'))\n",
        "    mae  = metrics.get('mae_score_global', float('nan'))\n",
        "    rmse = metrics.get('rmse_score_global', float('nan'))\n",
        "    h1   = metrics.get('h1_satisfied', False)\n",
        "    n    = metrics.get('n_evaluated', '?')\n",
        "    print('=' * 56)\n",
        "    print('H1 — Correlation Score_Global vs Gold')\n",
        "    print('=' * 56)\n",
        "    print(f'  n evalues   : {n}')\n",
        "    ok_p = 'H1 validee' if h1 else 'H1 non validee'\n",
        "    ok_s = 'ok' if metrics.get('h1_spearman_ok') else 'ko'\n",
        "    print(f'  Pearson r   : {r:.4f}  {ok_p} (seuil >= 0.60)')\n",
        "    print(f'  Spearman r  : {rho:.4f}  {ok_s} (seuil >= 0.55)')\n",
        "    print(f'  MAE         : {mae:.2f}')\n",
        "    print(f'  RMSE        : {rmse:.2f}')\n",
        "else:\n",
        "    print('Resultats H1 non disponibles. Lancez compute_metrics.py.')",
    ),
    code(
        "from evaluation.compute_metrics import load_gold, load_predictions\n",
        "\n",
        "if GOLD_PATH.exists() and PREDS_PATH.exists():\n",
        "    gold   = load_gold(str(GOLD_PATH))\n",
        "    preds  = load_predictions(str(PREDS_PATH))\n",
        "    merged = gold.merge(preds, on='comment_id', suffixes=('_gold', '_pred'))\n",
        "    if 'gold_score' in merged.columns and 'score_global' in merged.columns:\n",
        "        fig, ax = plt.subplots(figsize=(7, 5))\n",
        "        ax.scatter(merged['gold_score'], merged['score_global'],\n",
        "                   alpha=0.6, s=40, color='steelblue', edgecolors='white', linewidths=0.5)\n",
        "        ax.plot([0, 100], [0, 100], 'r--', lw=1, label='y = x')\n",
        "        ax.set_xlabel('Gold score [0-100]')\n",
        "        ax.set_ylabel('Score_Global predit [0-100]')\n",
        "        r_val = metrics.get('pearson_r', '?')\n",
        "        rho_val = metrics.get('spearman_r', '?')\n",
        "        ax.set_title(f'H1 — Pearson r={r_val}  Spearman r={rho_val}')\n",
        "        ax.legend()\n",
        "        plt.tight_layout()\n",
        "        plt.savefig(RESULTS_DIR / 'h1_scatter.png')\n",
        "        plt.show()\n",
        "else:\n",
        "    print('Gold ou predictions manquants.')",
    ),
    # ── 3. H2 ─────────────────────────────────────────────────────────────────
    md("## 3. H2 — Pipeline multi-agents vs LLM unique (baseline)"),
    code(
        "if baseline_cmp:\n",
        "    bl = baseline_cmp.get('baseline_llm_single', {})\n",
        "    pl = baseline_cmp.get('pipeline_multi_agent', {})\n",
        "    dr = baseline_cmp.get('delta_pearson_r', float('nan'))\n",
        "    h2 = baseline_cmp.get('h2_satisfied', False)\n",
        "    print('=' * 56)\n",
        "    print('H2 — Comparaison baseline vs pipeline')\n",
        "    print('=' * 56)\n",
        "    print(f'{\"Methode\":<30} {\"Pearson r\":>10} {\"MAE\":>8}')\n",
        "    print('-' * 56)\n",
        "    r_bl = bl.get('pearson_r', float('nan'))\n",
        "    m_bl = bl.get('mae', float('nan'))\n",
        "    r_pl = pl.get('pearson_r', float('nan'))\n",
        "    m_pl = pl.get('mae', float('nan'))\n",
        "    print(f'{\"LLM unique (baseline)\":<30} {r_bl:>10.4f} {m_bl:>8.2f}')\n",
        "    print(f'{\"Pipeline multi-agents\":<30} {r_pl:>10.4f} {m_pl:>8.2f}')\n",
        "    print('-' * 56)\n",
        "    ok_str = 'H2 validee (D > 0.10)' if h2 else 'H2 non validee (D <= 0.10)'\n",
        "    print(f'DeltaPearson r = {dr:+.4f}  {ok_str}')\n",
        "else:\n",
        "    print('Resultats H2 non disponibles. Lancez baseline_comparison.py.')",
    ),
    code(
        "if baseline_cmp:\n",
        "    bl = baseline_cmp.get('baseline_llm_single', {})\n",
        "    pl = baseline_cmp.get('pipeline_multi_agent', {})\n",
        "    methods = ['LLM unique\\n(baseline)', 'Pipeline\\nmulti-agents']\n",
        "    r_vals  = [bl.get('pearson_r', 0), pl.get('pearson_r', 0)]\n",
        "    fig, ax = plt.subplots(figsize=(5, 4))\n",
        "    bars = ax.bar(methods, r_vals, color=['#e07b54', '#4a90d9'], width=0.5, edgecolor='white')\n",
        "    ax.axhline(0.60, color='green', linestyle='--', lw=1.5, label='Seuil H1 (r=0.60)')\n",
        "    ax.set_ylim(0, 1.0)\n",
        "    ax.set_ylabel('Pearson r')\n",
        "    ax.set_title('H2 — Comparaison baseline vs pipeline')\n",
        "    for bar, val in zip(bars, r_vals):\n",
        "        ax.text(bar.get_x() + bar.get_width() / 2, val + 0.02, f'{val:.3f}', ha='center', fontsize=10)\n",
        "    ax.legend()\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(RESULTS_DIR / 'h2_comparison.png')\n",
        "    plt.show()",
    ),
    # ── 4. H4 ablation ────────────────────────────────────────────────────────
    md(
        "## 4. H4 — Ablation CoT / ToT / Tools (AC-09)\n",
        "\n",
        "Compare 4 conditions : B0 (prompt direct) | B1 (CoT) | B2 (CoT+ToT) | B3 (CoT+ToT+Tools)",
    ),
    code(
        "if ablation:\n",
        "    conds = ablation.get('conditions', {})\n",
        "    gains = ablation.get('gains_by_step', {})\n",
        "    h4    = ablation.get('h4', {})\n",
        "    print('=' * 72)\n",
        "    print('H4 — Ablation CoT / ToT / Tools')\n",
        "    print('=' * 72)\n",
        "    print(f'{\"Condition\":<35} {\"Pearson r\":>10} {\"MAE\":>7} {\"F1-sent\":>9} {\"Fallback\":>9}')\n",
        "    print('-' * 72)\n",
        "    for cid, res in conds.items():\n",
        "        f1 = f\"{res['f1_sentiment']:.4f}\" if res.get('f1_sentiment') is not None else '    N/A'\n",
        "        fb = res.get('fallback_rate', 0)\n",
        "        print(f\"  {cid} - {res['label']:<30} {res['pearson_r']:>10.4f} {res['mae']:>7.2f} {f1:>9} {fb:>8.1%}\")\n",
        "    print('-' * 72)\n",
        "    for step, vals in gains.items():\n",
        "        f1g = f\"{vals['delta_f1_pts']:+.1f} pts F1\" if vals.get('delta_f1_pts') is not None else 'N/A'\n",
        "        print(f'  Gain {step:<12} Dr={vals[\"delta_pearson_r\"]:+.4f}  {f1g}')\n",
        "    print('-' * 72)\n",
        "    print(h4.get('interpretation', ''))\n",
        "else:\n",
        "    print('Resultats H4 non disponibles. Lancez ablation_study.py.')",
    ),
    code(
        "if ablation:\n",
        "    conds = ablation.get('conditions', {})\n",
        "    cids   = list(conds.keys())\n",
        "    labels = [f\"{cid}\\n{conds[cid]['label'][:18]}\" for cid in cids]\n",
        "    r_vals = [conds[c]['pearson_r'] for c in cids]\n",
        "    f1_vals = [conds[c].get('f1_sentiment') or 0 for c in cids]\n",
        "    fb_vals = [conds[c].get('fallback_rate', 0) * 100 for c in cids]\n",
        "\n",
        "    fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n",
        "\n",
        "    axes[0].bar(cids, r_vals, color=['#aaa', '#7bc8a4', '#4a90d9', '#1a4a8a'], edgecolor='white')\n",
        "    axes[0].set_ylim(0, 1)\n",
        "    axes[0].axhline(0.60, color='red', linestyle='--', lw=1, label='seuil H1')\n",
        "    axes[0].set_title('Pearson r par condition')\n",
        "    axes[0].set_ylabel('Pearson r')\n",
        "    axes[0].legend(fontsize=8)\n",
        "\n",
        "    axes[1].bar(cids, [v * 100 for v in f1_vals], color=['#aaa', '#7bc8a4', '#4a90d9', '#1a4a8a'], edgecolor='white')\n",
        "    axes[1].axhline(75, color='orange', linestyle='--', lw=1, label='seuil F1 75')\n",
        "    axes[1].set_ylim(0, 100)\n",
        "    axes[1].set_title('F1-macro sentiment (%)')\n",
        "    axes[1].set_ylabel('F1 (%)')\n",
        "    axes[1].legend(fontsize=8)\n",
        "\n",
        "    axes[2].bar(cids, fb_vals, color=['#aaa', '#7bc8a4', '#4a90d9', '#1a4a8a'], edgecolor='white')\n",
        "    axes[2].axhline(5, color='red', linestyle='--', lw=1, label='seuil 5%')\n",
        "    axes[2].set_title('Taux de fallback (%)')\n",
        "    axes[2].set_ylabel('Fallback (%)')\n",
        "    axes[2].legend(fontsize=8)\n",
        "\n",
        "    plt.suptitle('H4 — Ablation CoT / ToT / Tools (AC-09)', fontsize=12, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig(RESULTS_DIR / 'h4_ablation.png')\n",
        "    plt.show()",
    ),
    # ── 5. Métriques sentiment et bruit ───────────────────────────────────────
    md("## 5. Metriques sentiment et bruit"),
    code(
        "if metrics:\n",
        "    acc = metrics.get('sentiment_accuracy')\n",
        "    f1  = metrics.get('sentiment_f1_macro')\n",
        "    kap = metrics.get('sentiment_kappa')\n",
        "    fb  = metrics.get('fallback_rate')\n",
        "    if acc is not None:\n",
        "        print('-- Sentiment (3 classes) --')\n",
        "        print(f'  Accuracy  : {acc:.4f}')\n",
        "        print(f'  F1-macro  : {f1:.4f}  {\"ok > 0.75\" if f1 and f1 > 0.75 else \"ko <= 0.75\"}')\n",
        "        kap_str = 'ok kappa > 0.70' if kap and kap > 0.70 else 'ko kappa <= 0.70'\n",
        "        print(f'  Kappa     : {kap:.4f}  {kap_str}')\n",
        "    if fb is not None:\n",
        "        fb_str = 'ok < 5%' if fb < 0.05 else 'KO >= 5%'\n",
        "        print(f'\\n-- Fallback LLM (NFR-09) --')\n",
        "        print(f'  Taux     : {fb:.1%}  {fb_str}')\n",
        "if errors:\n",
        "    noise = errors.get('noise_detection', {})\n",
        "    if noise.get('available'):\n",
        "        print('\\n-- Bruit (A5) --')\n",
        "        print(f'  Precision : {noise[\"precision\"]:.3f}')\n",
        "        print(f'  Rappel    : {noise[\"recall\"]:.3f}')\n",
        "        print(f'  F1        : {noise[\"f1\"]:.3f}  {\"ok > 0.70\" if noise[\"f1\"] > 0.70 else \"ko <= 0.70\"}')",
    ),
    # ── 6. Taux de fallback par agent ─────────────────────────────────────────
    md("## 6. Taux de fallback et hallucination_flags"),
    code(
        "if errors:\n",
        "    hflags = errors.get('hallucination_flags_count', {})\n",
        "    fb_by_agent = errors.get('fallback_by_agent', {})\n",
        "\n",
        "    if fb_by_agent:\n",
        "        agents = list(fb_by_agent.keys())\n",
        "        rates  = [fb_by_agent[a] * 100 for a in agents]\n",
        "        fig, ax = plt.subplots(figsize=(6, 4))\n",
        "        colors = ['#e07b54' if r >= 5 else '#4a90d9' for r in rates]\n",
        "        ax.bar(agents, rates, color=colors, edgecolor='white')\n",
        "        ax.axhline(5, color='red', linestyle='--', lw=1.5, label='Seuil NFR-09 (5%)')\n",
        "        ax.set_ylabel('Taux de fallback (%)')\n",
        "        ax.set_title('Fallback heuristique par agent')\n",
        "        ax.legend()\n",
        "        plt.tight_layout()\n",
        "        plt.savefig(RESULTS_DIR / 'fallback_by_agent.png')\n",
        "        plt.show()\n",
        "    else:\n",
        "        print('Donnees fallback par agent non disponibles dans error_analysis.json')\n",
        "\n",
        "    if hflags:\n",
        "        print('\\nhallucination_flags detectes :')\n",
        "        for flag, count in hflags.items():\n",
        "            print(f'  {flag:<40} : {count}')\n",
        "else:\n",
        "    print('Analyse erreurs non disponible. Lancez error_analysis.py.')",
    ),
    # ── 7. Outliers de score ───────────────────────────────────────────────────
    md("## 7. Analyse des outliers de score"),
    code(
        "if errors:\n",
        "    n_out = errors.get('n_outliers', 0)\n",
        "    rate  = errors.get('outlier_rate', 0)\n",
        "    thr   = errors.get('outlier_threshold', 20)\n",
        "    items = errors.get('score_outliers', [])\n",
        "    print(f'Outliers (|err| > {thr}) : {n_out} ({rate:.1%})')\n",
        "    if items:\n",
        "        df_out = pd.DataFrame(items[:10])\n",
        "        display(df_out[['comment_id', 'gold_score', 'pred_score', 'abs_error', 'direction']])\n",
        "else:\n",
        "    print('Analyse erreurs non disponible. Lancez error_analysis.py.')",
    ),
    # ── 8. Recapitulatif final ─────────────────────────────────────────────────
    md("## 8. Recapitulatif final — Validation des hypotheses"),
    code(
        "print('=' * 70)\n",
        "print('RECAPITULATIF — Validation des hypotheses (PRD v3.0)')\n",
        "print('=' * 70)\n",
        "\n",
        "def _status(val, threshold, direction='>=', fmt='.4f'):\n",
        "    if val is None:\n",
        "        return 'N/A'\n",
        "    ok = (val >= threshold) if direction == '>=' else (val > threshold)\n",
        "    symbol = 'OK' if ok else 'KO'\n",
        "    return f'{symbol}  {val:{fmt}}'\n",
        "\n",
        "h1_r   = metrics.get('pearson_r') if metrics else None\n",
        "h1_rho = metrics.get('spearman_r') if metrics else None\n",
        "h2_dr  = baseline_cmp.get('delta_pearson_r') if baseline_cmp else None\n",
        "h4_ok  = ablation.get('h4', {}).get('h4_satisfied') if ablation else None\n",
        "h4_f1g = ablation.get('h4', {}).get('delta_f1_pts_b0_b3') if ablation else None\n",
        "fb     = metrics.get('fallback_rate') if metrics else None\n",
        "\n",
        "print(f'H1 Pearson r >= 0.60        : {_status(h1_r, 0.60)}')\n",
        "print(f'H1 Spearman r >= 0.55       : {_status(h1_rho, 0.55)}')\n",
        "print(f'H2 DeltaPearson > 0.10      : {_status(h2_dr, 0.10, \">\")}')\n",
        "print(f'H4 Gain F1 B0->B3 >= 15 pts : {_status(h4_f1g, 15.0, \">=\", \".1f\") if h4_f1g is not None else \"N/A\"}')\n",
        "print(f'NFR-09 Fallback < 5%        : {_status(fb, 0.05, \"<\", \".1%\") if fb is not None else \"N/A\"}')\n",
        "h4_str = 'OK validee' if h4_ok else ('KO non validee' if h4_ok is not None else 'N/A')\n",
        "print(f'H4 satisfaite               : {h4_str}')\n",
        "print('=' * 70)",
    ),
]

# Assign cell IDs
for i, cell in enumerate(cells_raw):
    cell["id"] = f"p5c{i:02d}"

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells_raw,
}

out = Path(__file__).parent.parent / "notebooks" / "phase5_evaluation.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Written {out.stat().st_size:,} bytes -> {out}")
